- name: 创建docker挂载的目录
  shell: mkdir -p {{ item }}
  with_items:
  - /data/db/rabbitmq/config
  - /data/icsoc


- name: 拷贝rabbitmq的docker-compose文件
  template: src=docker-rabbitmq-composer.yml.j2 dest=/data/icsoc/docker-rabbitmq-composer.yml

- name: 启动rabbitmq：
  shell: docker-compose -f /data/icsoc/docker-rabbitmq-composer.yml up -d

- name:
  shell: docker exec rabbitmq bash -c "rabbitmqctl stop_app;rabbitmqctl join_cluster rabbit@{{ MasterRabbitMq }};rabbitmqctl start_app;"
  when: ansible_default_ipv4.address != "{{ MasterRabbitMqIp }}"

