- name: 创建docker挂载的目录
  shell: mkdir -p {{ item }}
  with_items:
  - /data/db/rabbitmq/config
  - /data/icsoc


- name: 拷贝rabbitmq的docker-compose文件
  template: src=docker-rabbitmq-composer.yml.j2 dest=/home/icsoc/docker-rabbitmq-composer.yml

-nmae:
  shell:
